import mongoose from "mongoose";
import dotenv from "dotenv";
import { Movie } from "../models/Movie";

dotenv.config();

const sampleMovies = [
    {
        title: "The Shawshank Redemption",
        year: 1994,
        rating: 9.3,
        director: "Frank Darabont",
        genre: ["Drama"],
        plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        cast: ["Tim Robbins", "Morgan Freeman"],
        rank: 1,
        imdbId: "tt0111161",
    },
    {
        title: "The Godfather",
        year: 1972,
        rating: 9.2,
        director: "Francis Ford Coppola", 
        genre: ["Crime", "Drama"],
        plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        cast: ["Marlon Brando", "Al Pacino"],
        rank: 2,
        imdbId: "tt0068646",
    },
    {
        title: "The Dark Knight",
        year: 2008,
        rating: 9.0,
        director: "Christopher Nolan",
        genre: ["Action", "Crime", "Drama"],
        plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        cast: ["Christian Bale", "Heath Ledger"],
        rank: 3,
        imdbId: "tt0468569",
    },
    {
        title: "The Godfather Part II",
        year: 1974,
        rating: 9.0,
        director: "Francis Ford Coppola",
        genre: ["Crime", "Drama"],
        plot: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
        cast: ["Al Pacino", "Robert Duvall"],
        rank: 4,
        imdbId: "tt0071562",
    },
    {
        title: "12 Angry Men",
        year: 1957,
        rating: 9.0,
        director: "Sidney Lumet",
        genre: ["Drama"],
        plot: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
        cast: ["Henry Fonda", "Lee J. Cobb"],
        rank: 5,
        imdbId: "tt0050083",
    },
    {
        title: "Schindler's List",
        year: 1993,
        rating: 8.9,
        director: "Steven Spielberg",
        genre: ["Biography", "Drama", "History"],
        plot: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        cast: ["Liam Neeson", "Ben Kingsley"],
        rank: 6,
        imdbId: "tt0108052",
    },
    {
        title: "The Lord of the Rings: The Return of the King",
        year: 2003,
        rating: 8.9,
        director: "Peter Jackson",
        genre: ["Action", "Adventure", "Drama"],
        plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        cast: ["Elijah Wood", "Viggo Mortensen"],
        rank: 7,
        imdbId: "tt0167260",
    },
    {
        title: "Pulp Fiction",
        year: 1994,
        rating: 8.9,
        director: "Quentin Tarantino",
        genre: ["Crime", "Drama"],
        plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        cast: ["John Travolta", "Samuel L. Jackson"],
        rank: 8,
        imdbId: "tt0110912",
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        year: 2001,
        rating: 8.8,
        director: "Peter Jackson",
        genre: ["Action", "Adventure", "Drama"],
        plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        cast: ["Elijah Wood", "Ian McKellen"],
        rank: 9,
        imdbId: "tt0120737",
    },
    {
        title: "The Good, the Bad and the Ugly",
        year: 1966,
        rating: 8.8,
        director: "Sergio Leone",
        genre: ["Western"],
        plot: "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
        cast: ["Clint Eastwood", "Eli Wallach"],
        rank: 10,
        imdbId: "tt0060196",
    },
    {
        title: "Forrest Gump",
        year: 1994,
        rating: 8.8,
        director: "Robert Zemeckis",
        genre: ["Drama", "Romance"],
        plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
        cast: ["Tom Hanks", "Robin Wright"],
        rank: 11,
        imdbId: "tt0109830",
    },
    {
        title: "Fight Club",
        year: 1999,
        rating: 8.8,
        director: "David Fincher",
        genre: ["Drama"],
        plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        cast: ["Brad Pitt", "Edward Norton"],
        rank: 12,
        imdbId: "tt0137523",
    },
    {
        title: "Inception",
        year: 2010,
        rating: 8.8,
        director: "Christopher Nolan",
        genre: ["Action", "Adventure", "Sci-Fi"],
        plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
        rank: 13,
        imdbId: "tt1375666",
    },
    {
        title: "The Matrix",
        year: 1999,
        rating: 8.7,
        director: "Lana Wachowski",
        genre: ["Action", "Sci-Fi"],
        plot: "A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.",
        cast: ["Keanu Reeves", "Laurence Fishburne"],
        rank: 14,
        imdbId: "tt0133093",
    },
    {
        title: "Goodfellas",
        year: 1990,
        rating: 8.7,
        director: "Martin Scorsese",
        genre: ["Biography", "Crime", "Drama"],
        plot: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.",
        cast: ["Robert De Niro", "Ray Liotta"],
        rank: 15,
        imdbId: "tt0099685",
    },
    {
        title: "One Flew Over the Cuckoo's Nest",
        year: 1975,
        rating: 8.7,
        director: "Milos Forman",
        genre: ["Drama"],
        plot: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.",
        cast: ["Jack Nicholson", "Louise Fletcher"],
        rank: 16,
        imdbId: "tt0073486",
    },
    {
        title: "Seven Samurai",
        year: 1954,
        rating: 8.6,
        director: "Akira Kurosawa",
        genre: ["Action", "Drama"],
        plot: "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
        cast: ["Toshiro Mifune", "Takashi Shimura"],
        rank: 17,
        imdbId: "tt0047478",
    },
    {
        title: "Se7en",
        year: 1995,
        rating: 8.6,
        director: "David Fincher",
        genre: ["Crime", "Drama", "Mystery"],
        plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        cast: ["Brad Pitt", "Morgan Freeman"],
        rank: 18,
        imdbId: "tt0114369",
    },
    {
        title: "The Silence of the Lambs",
        year: 1991,
        rating: 8.6,
        director: "Jonathan Demme",
        genre: ["Crime", "Drama", "Thriller"],
        plot: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
        cast: ["Jodie Foster", "Anthony Hopkins"],
        rank: 19,
        imdbId: "tt0102926",
    },
    {
        title: "City of God",
        year: 2002,
        rating: 8.6,
        director: "Fernando Meirelles",
        genre: ["Crime", "Drama"],
        plot: "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.",
        cast: ["Alexandre Rodrigues", "Leandro Firmino"],
        rank: 20,
        imdbId: "tt0317248",
    },
    {
        title: "Saving Private Ryan",
        year: 1998,
        rating: 8.6,
        director: "Steven Spielberg",
        genre: ["Drama", "War"],
        plot: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        cast: ["Tom Hanks", "Matt Damon"],
        rank: 21,
        imdbId: "tt0120815",
    },
    {
        title: "Life Is Beautiful",
        year: 1997,
        rating: 8.6,
        director: "Roberto Benigni",
        genre: ["Comedy", "Drama", "Romance"],
        plot: "When an open-minded Jewish librarian and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.",
        cast: ["Roberto Benigni", "Nicoletta Braschi"],
        rank: 22,
        imdbId: "tt0118799",
    },
    // Add more movies as needed...
];

const seedDatabase = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI!);
        console.log("Connected to MongoDB");

        await Movie.deleteMany({});
        console.log("Cleared existing movies");

        await Movie.insertMany(sampleMovies);
        console.log("Sample movies added successfully");

        await mongoose.disconnect();
        console.log("Disconnected from MongoDB");
    } catch (error) {
        console.error("Error seeding database:", error);
        process.exit(1);
    }
};

seedDatabase();
